/* Generated By:JavaCC: Do not edit this line. MELAParametersConstants.java */
package mela.io;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MELAParametersConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 7;
  /** RegularExpression Id. */
  int FLOAT = 8;
  /** RegularExpression Id. */
  int FLOAT_SCIENTIFIC = 9;
  /** RegularExpression Id. */
  int EXPONENT = 10;
  /** RegularExpression Id. */
  int LETTER = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int WORD = 13;
  /** RegularExpression Id. */
  int KEYWORD_RUN = 14;
  /** RegularExpression Id. */
  int KEYWORD_STOP = 15;
  /** RegularExpression Id. */
  int KEYWORD_TIME = 16;
  /** RegularExpression Id. */
  int KEYWORD_POPULATION = 17;
  /** RegularExpression Id. */
  int KEYWORD_POPLOC = 18;
  /** RegularExpression Id. */
  int KEYWORD_ACTION = 19;
  /** RegularExpression Id. */
  int KEYWORD_STEP = 20;
  /** RegularExpression Id. */
  int KEYWORD_TIMEBOUND = 21;
  /** RegularExpression Id. */
  int KEYWORD_TOTAL = 22;
  /** RegularExpression Id. */
  int KEYWORD_COUNT = 23;
  /** RegularExpression Id. */
  int SEMICOLON = 24;
  /** RegularExpression Id. */
  int ASSIGN = 25;
  /** RegularExpression Id. */
  int COMMA = 26;
  /** RegularExpression Id. */
  int LR = 27;
  /** RegularExpression Id. */
  int RR = 28;
  /** RegularExpression Id. */
  int INT = 29;
  /** RegularExpression Id. */
  int DOUBLE = 30;
  /** RegularExpression Id. */
  int IDENTIFIER = 31;
  /** RegularExpression Id. */
  int MATH_EXPR = 32;
  /** RegularExpression Id. */
  int SPACE = 33;
  /** RegularExpression Id. */
  int M_AND = 34;
  /** RegularExpression Id. */
  int M_OR = 35;
  /** RegularExpression Id. */
  int M_LINER = 36;
  /** RegularExpression Id. */
  int M_LINEN = 37;
  /** RegularExpression Id. */
  int SYMBOL = 38;
  /** RegularExpression Id. */
  int PARAM_SYMBOL = 39;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int RESET = 1;
  /** Lexical state. */
  int ID = 2;
  /** Lexical state. */
  int MATH = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER>",
    "<FLOAT>",
    "<FLOAT_SCIENTIFIC>",
    "<EXPONENT>",
    "<LETTER>",
    "<DIGIT>",
    "<WORD>",
    "\"#Runs\"",
    "\"#Stopping Predicate\"",
    "\"#Time\"",
    "\"#Population\"",
    "\"#Pop_Loc\"",
    "\"#ActionCount\"",
    "\"#Steps\"",
    "\"#Time bound\"",
    "\"#Total population\"",
    "\"#Action\"",
    "\":\"",
    "\"=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "<INT>",
    "<DOUBLE>",
    "<IDENTIFIER>",
    "<MATH_EXPR>",
    "<SPACE>",
    "\"&&\"",
    "\"|\"",
    "\"\\r\"",
    "\"\\n\"",
    "<SYMBOL>",
    "<PARAM_SYMBOL>",
  };

}
